# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscelaneous
favicon: /favicon.png
